### ISSUE TITLE
slow run time

### ISSUE THREAD

**Issue by meatric** [kjokjo/ipcalc#5]
Hi,

When I calculate a bigger subnet with the v0.51, the run time is slower with than v0.41.

Here is an example:

time ./ipcalc.0.41 -bn 10.0.0.0/24 30
....
real	0m0,015s
user	0m0,010s
sys	0m0,005s

time ./ipcalc.0.51 -bn 10.0.0.0/24 30
....
real	0m1,879s
user	0m1,622s
sys	0m0,256s

**Comment by kjokjo** [comment]
Hey meatric,

that's a sacrifice to ipv6 support. If you don't care for ipv6 calculations comment out `use bignum;` and it's as fast as before. But ipv6 calculations are wrong then 🤣
